version: '3'
services:
  db:
    image: mysql:5.7
    command: --lower_case_table_names=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    networks:
      - net
    ports:
      - "3306:3306"
    volumes:
      - databases:/var/lib/mysql
      - ./init/01.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./modules/yourstore-be/yourstore-ms-store/sql/permissions.sql:/docker-entrypoint-initdb.d/02-init.sql
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 20m

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
      - TZ="Europe/Rome"
      - PMA_HOSTS=db
    networks:
      - net
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 20m

  keycloak:
    image: jboss/keycloak:14.0.0
    networks:
      - net
    ports:
      - 8282:8080
    environment:
      DB_VENDOR: MYSQL
      DB_DATABASE: keycloak
      DB_ADDR: db
      DB_PORT: 3306
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      JDBC_PARAMS: "useSSL=false"
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - db
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 20m

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - net
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - net
    ports:
      - "9090:9000/tcp"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]

  yourstore-ms-store:
    image: yourstore-ms-store:0.0.1-SNAPSHOT
    environment:
      PORT: 8080
      KK_URL: http://keycloak
      KK_PORT: 8080
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.platform.os == linux ]
    ports:
      - "8081:8080/tcp"
    build:
      context: modules/yourstore-be/yourstore-ms-store
      dockerfile: Dockerfile
    depends_on:
      - keycloak
  yourstore-gateway:
    image: yourstore-gateway:0.0.1-SNAPSHOT
    environment:
      STORE_URL: yourstore-ms-store
      STORE_PORT: 8080
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.platform.os == linux ]
    ports:
      - "8090:8080/tcp"
    build:
      context: modules/yourstore-be/yourstore-gateway
      dockerfile: Dockerfile
    depends_on:
      - keycloak

volumes:
  portainer_data:
  databases:
networks:
  net:
    driver: overlay

