INSERT INTO PRODUCT VALUES(1);
INSERT INTO PRODUCT VALUES(2);

INSERT INTO UTENTE VALUES(1, 'paolo99.caruso@gmail.com', 'true', 'Paolo', '1', 'Caruso');

INSERT INTO ORDINE VALUES(1, 'Via Verdello, 2', '2022-09-30', 120, 1);

INSERT INTO ORDER_ITEM VALUES(1, 1, 10);
INSERT INTO ORDER_ITEM VALUES(1, 2, 4);