package it.YourOnlineStore.Database;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;

@Controller // This means that this class is a Controller
@RequestMapping(path="/Database") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ProductRepository productRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody Integer addNewProduct (@RequestParam String productName
            , @RequestParam Float cost, @RequestParam Integer disponibility, @RequestParam String imageUrl, @RequestParam String description) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Product product = new Product();
        product.setProductName(productName);
        product.setCost(cost);
        product.setDisponibiliy(disponibility);
        product.setImage(imageUrl);
        product.setDescription(description);
        productRepository.save(product);
        return product.getProductId();
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Product> getAllUsers() {
        // This returns a JSON or XML with the users
        return productRepository.findAll();
    }

    @GetMapping(path="/buy")
    public @ResponseBody boolean buyProduct(@RequestParam Integer id){
        Optional<Product> product = productRepository.findById(id);
        product.ifPresent(Product::buy);
        productRepository.save(product.get());
        return product.isPresent();
    }

    @GetMapping(path="/get")
    public @ResponseBody Optional<Product> getProduct(@RequestParam Integer id){
        return productRepository.findById(id);
    }

    @GetMapping(path="/error")
    public @ResponseBody String error(){
        return "Error Page";
    }


}